name: authivate
description: The Dart SDK for the Authivate service
version: 0.1.0+1

repository: https://github.com/PeterAkande/autivate_dart

dependencies:
  http: ^1.1.0
  dartz: ^0.10.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
